version: "3.5"

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./secrets:/app/secrets:ro
      - ./config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    shm_size: '2gb'
